version: '3.2'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - type: bind
        source: ./yousan/add-page-from-template
        target: /var/www/html/wp-content/plugins/add-page-from-template/
      - type: bind
        source: ./apft
        target: /var/www/html/wp-content/plugins/apft/

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example